remote_theme: yaoyao-liu/minimal-light
# Basic Information 
title: Ruoyu Li
position: 4-th year Ph.D. Candidate
affiliation: Tsinghua University
email: liry19 (at) mails.tsinghua.edu.cn

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: ruoyu li
description: This is Ruoyu Li's personal webpage.
canonical: https://ruoyu-li.github.io

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/
# cv_link: files/Curriculum_Vitae.pdf
linkedin: https://www.linkedin.com/in/ruoyu-li-560529139/
github_link: https://github.com/Ruoyu-Li/
#twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: avatar.jpeg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
